### ISSUE TITLE
Is this plugin ready for 6.6?

### ISSUE THREAD

**Issue by Tim-VL** [AREA-NET-GmbH-Shopware-Agentur/plugin-default-product-layout#2]
Hi

Can we use this plugin also on 6.6?

Thanks!

**Comment by areanet-schmid** [comment]
We have released the version 3.0.0 for Shopware 6.6 support: https://github.com/AREA-NET-GmbH-Shopware-Agentur/plugin-default-product-layout/releases/tag/3.0.0
